name: Pull Request
description: Add a new pull request
title: ""
labels: [""]
body:
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Please include the version of the app you're working on.
      placeholder: e.g. 1.0.1
    validations:
      required: true
  - type: input
    id: windows-build
    attributes:
      label: Windows Build
      description: Please include the version and build number of Windows you're using.
      placeholder: e.g. Windows 10 Build 19042
    validations:
      required: true
  - type: input
    id: finger-size
    attributes:
      label: Finger Size
      description: Please provide a rough estimation of the finger size used on the device, in either length or diameter (mm).
      placeholder: e.g. 15mm
    validations:
      required: true
  - type: textarea
    id: changes-made
    attributes:
      label: Changes Made
      description: Please describe the changes that you made.
      placeholder: Describe your changes here.
    validations:
      required: true
  - type: textarea
    id: test-plan
    attributes:
      label: Test Plan
      description: Describe the tests that you ran to verify your changes.
      placeholder: Describe the tests you ran here.
    validations:
      required: true
