#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "Validating Javascript:"

# Check for eslint
which eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "Please install ESlint [npm install eslint --save-dev]"
  exit 1
fi

for FILE in $STAGED_FILES
do
  if [["$FILE" != ".eslintrc.js"]]; then
    eslint --quiet --fix "$FILE"
  
    if [[ "$?" == 0 ]]; then
      echo "ESLint Passed: $FILE"
    else
      echo "ESLint Failed: $FILE"
      PASS=false
    fi
  fi
done

echo "Javascript validation completed!"

if ! $PASS; then
  echo "COMMIT FAILED: Please fix the ESLint errors and try again."
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

exit $?
